server:
  port: 10007
spring:
  application:
    name: ds-authentication
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
leon:
  jwt:
    secret: leon@Login(Authentication}*^31)&dazzlingShop% # 登录校验的密钥
    pubKeyPath: C:\\Users\\Administrator\\Desktop\\rsa\\rsa.pub # 公钥地址
    priKeyPath: C:\\Users\\Administrator\\Desktop\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: DS_TOKEN
    cookieMaxAge: 30
