server:
  port: 8081
spring:
  application:
    name: ds-item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leon
    username: root
    password: 512321
    driver-class-name: com.mysql.jdbc.Driver


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
#mybatis:
#  type-aliases-package: org.spring.springboot.domain
#  mapper-locations: mapper/*.xml
