server:
  port: 8086
spring:
  application:
    name: ds-sms
  rabbitmq:
    host: 192.168.0.55
    username: leon
    password: leon
    virtual-host: /leon
leon:
  sms:
    accessKeyId: JokbYfJiIJHkb # 自己的accessKeyId
    accessKeySecret: kaG2dahUH8da1jnjKMKg # 自己的accessSecret
    signName: leon # 签名名称
    verifyCodeTemplate: SMS_17882937625 # 模板名称
